### ISSUE TITLE
Peer-to-peer Code Review

### ISSUE THREAD

**Issue by fredericomba** [ricardovaltierra/design-your-own-grid-based-framework#2]
The project is good and the code is clean.
To use @import in many of your rules is a good practice.

- All elements have the same width, so why not just use the default rule?
- The patwright course suggested using three media screen breakpoints (your page is working fine in that requisite), but some people also use their phones in landscape mode (so remember that and consider adding breakpoints for handling these scenarios).
- Line 12 HTML - your favicon isn't working as it may need to be declared (for Mac OSX at least) as: <link rel="icon" href=".." type="image/png"> 
- @import at would be better in the CSS (instead of the HTML code).
- add some classes to required properties on the framework like margins, padding, floats, positions, border etc.
- add sass-cache to .gitignore
- add some descriptive comments to CSS and HTML in order to have a more easily reading and identify each section of the site.

**Comment by ricardovaltierra** [comment]
Most of the advices taken, all issues resolved but the icon-Mac one.
